version: "3.8"

services:
    redis:
        image: redis
        ports:
            - "6379:6379"
    server:
        image: server
        ports:
            - 4000:4000
        depends_on:
            - redis
        environment:
            REDIS_HOST: redis

    client:
        image: client
        ports:
            - 3000:3000